spring:
  datasource:
    username: root
    password: clearlove7
    url: jdbc:mysql://localhost:3306/yunxing2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver